"""add_portfolio_snapshots

Revision ID: 301a773c180c
Revises: 9acdb1053463
Create Date: 2026-04-05 14:51:03.593989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '301a773c180c'
down_revision: Union[str, Sequence[str], None] = '9acdb1053463'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('cash_available', sa.Float(), nullable=False),
    sa.Column('opening_balance', sa.Float(), nullable=False),
    sa.Column('holdings_value', sa.Float(), nullable=False),
    sa.Column('unrealized_pnl', sa.Float(), nullable=False),
    sa.Column('holdings_json', sa.JSON(), nullable=False),
    sa.Column('positions_json', sa.JSON(), nullable=False),
    sa.Column('reconciled_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_date')
    )
    op.create_index('ix_portfolio_snapshot_date', 'portfolio_snapshots', ['snapshot_date'], unique=False)
    op.create_table('stock_ensemble_weights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ensemble_config_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('knn_weight', sa.Float(), nullable=False),
    sa.Column('lstm_weight', sa.Float(), nullable=False),
    sa.Column('calibration_precision', sa.Float(), nullable=True),
    sa.Column('calibrated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ensemble_config_id'], ['ensemble_configs.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sew_config_stock', 'stock_ensemble_weights', ['ensemble_config_id', 'stock_id'], unique=False)
    op.create_index('ix_ensemble_pred_date_conf', 'ensemble_predictions', ['date', 'interval', 'confidence'], unique=False)
    op.create_index('ix_lstm_pred_date_conf', 'lstm_predictions', ['date', 'interval', 'confidence'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lstm_pred_date_conf', table_name='lstm_predictions')
    op.drop_index('ix_ensemble_pred_date_conf', table_name='ensemble_predictions')
    op.drop_index('ix_sew_config_stock', table_name='stock_ensemble_weights')
    op.drop_table('stock_ensemble_weights')
    op.drop_index('ix_portfolio_snapshot_date', table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    # ### end Alembic commands ###
