"""add_corporate_action_blocks_table

Revision ID: 3f5df04a428d
Revises: 4c5301dc82fc
Create Date: 2026-04-05 16:08:37.498342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f5df04a428d'
down_revision: Union[str, Sequence[str], None] = '4c5301dc82fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate_action_blocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('gap_pct', sa.Float(), nullable=False),
    sa.Column('blocked_until', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ca_block_symbol_expiry', 'corporate_action_blocks', ['symbol', 'blocked_until'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ca_block_symbol_expiry', table_name='corporate_action_blocks')
    op.drop_table('corporate_action_blocks')
    # ### end Alembic commands ###
