"""replace_golden_pattern_feature_window_with_parquet_filepath

Revision ID: 4c5301dc82fc
Revises: 301a773c180c
Create Date: 2026-04-05 15:29:37.774361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c5301dc82fc'
down_revision: Union[str, Sequence[str], None] = '301a773c180c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('golden_patterns', sa.Column('dataset_filepath', sa.String(length=500), nullable=False))
    op.add_column('golden_patterns', sa.Column('row_index', sa.Integer(), nullable=False))
    op.drop_column('golden_patterns', 'feature_window')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('golden_patterns', sa.Column('feature_window', sa.BLOB(), nullable=False))
    op.drop_column('golden_patterns', 'row_index')
    op.drop_column('golden_patterns', 'dataset_filepath')
    # ### end Alembic commands ###
