"""add_stationary_ml_features

Revision ID: a5ebeaf4bb4e
Revises: 68d371710d95
Create Date: 2026-04-10 21:26:34.485258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a5ebeaf4bb4e'
down_revision: Union[str, Sequence[str], None] = '68d371710d95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema — add 15 stationary ML feature columns to stock_indicators."""
    op.add_column('stock_indicators', sa.Column('dist_sma_50', sa.Float(), nullable=True))
    op.add_column('stock_indicators', sa.Column('dist_sma_200', sa.Float(), nullable=True))
    op.add_column('stock_indicators', sa.Column('roc_1', sa.Float(), nullable=True))
    op.add_column('stock_indicators', sa.Column('roc_5', sa.Float(), nullable=True))
    op.add_column('stock_indicators', sa.Column('roc_20', sa.Float(), nullable=True))
    op.add_column('stock_indicators', sa.Column('atr_pct', sa.Float(), nullable=True))
    op.add_column('stock_indicators', sa.Column('realized_vol_20', sa.Float(), nullable=True))
    op.add_column('stock_indicators', sa.Column('bb_pctb', sa.Float(), nullable=True))
    op.add_column('stock_indicators', sa.Column('bb_width', sa.Float(), nullable=True))
    op.add_column('stock_indicators', sa.Column('cmf_20', sa.Float(), nullable=True))
    op.add_column('stock_indicators', sa.Column('dist_vwap_5', sa.Float(), nullable=True))
    op.add_column('stock_indicators', sa.Column('macd_hist_norm', sa.Float(), nullable=True))
    op.add_column('stock_indicators', sa.Column('adx_norm', sa.Float(), nullable=True))
    op.add_column('stock_indicators', sa.Column('adx_pos_norm', sa.Float(), nullable=True))
    op.add_column('stock_indicators', sa.Column('adx_neg_norm', sa.Float(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_indicators', 'adx_neg_norm')
    op.drop_column('stock_indicators', 'adx_pos_norm')
    op.drop_column('stock_indicators', 'adx_norm')
    op.drop_column('stock_indicators', 'macd_hist_norm')
    op.drop_column('stock_indicators', 'dist_vwap_5')
    op.drop_column('stock_indicators', 'cmf_20')
    op.drop_column('stock_indicators', 'bb_width')
    op.drop_column('stock_indicators', 'bb_pctb')
    op.drop_column('stock_indicators', 'realized_vol_20')
    op.drop_column('stock_indicators', 'atr_pct')
    op.drop_column('stock_indicators', 'roc_20')
    op.drop_column('stock_indicators', 'roc_5')
    op.drop_column('stock_indicators', 'roc_1')
    op.drop_column('stock_indicators', 'dist_sma_200')
    op.drop_column('stock_indicators', 'dist_sma_50')
    op.alter_column('prediction_jobs', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('prediction_jobs', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('prediction_jobs', 'completed_stocks',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('prediction_jobs', 'total_stocks',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('prediction_jobs', 'progress',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('prediction_jobs', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               nullable=True,
               existing_server_default=sa.text("'running'"))
    op.drop_index('ix_ensemble_pred_run_at', table_name='ensemble_predictions')
    op.drop_index('ix_ensemble_pred_batch', table_name='ensemble_predictions')
    op.create_index(op.f('uq_ensemble_pred'), 'ensemble_predictions', ['ensemble_config_id', 'stock_id', 'date', 'interval'], unique=True)
    op.alter_column('ensemble_predictions', 'run_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###
