"""initial_schema

Revision ID: ceb765788569
Revises: 
Create Date: 2026-03-30 08:51:48.962982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceb765788569'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nse_holidays',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('week_day', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trading_date')
    )
    op.create_table('rl_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('algorithm', sa.String(length=50), nullable=False),
    sa.Column('hyperparams', sa.JSON(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('training_config', sa.JSON(), nullable=True),
    sa.Column('regime_filter', sa.JSON(), nullable=True),
    sa.Column('interval', sa.Enum('day', 'week', name='intervalenum'), nullable=False),
    sa.Column('total_reward', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('model_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('pending', 'training', 'completed', 'failed', name='modelstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property')
    )
    op.create_table('stocks_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('kite_id', sa.Integer(), nullable=True),
    sa.Column('tick_size', sa.Float(), nullable=True),
    sa.Column('lot_size', sa.Integer(), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('backtest_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_type', sa.String(length=20), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.Column('interval', sa.Enum('day', 'week', name='intervalenum'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_return', sa.Float(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('sharpe', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('trades_count', sa.Integer(), nullable=True),
    sa.Column('trade_log', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('golden_patterns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rl_model_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('interval', sa.Enum('day', 'week', name='intervalenum'), nullable=False),
    sa.Column('feature_window', sa.LargeBinary(), nullable=False),
    sa.Column('label', sa.Integer(), nullable=False),
    sa.Column('pnl_percent', sa.Float(), nullable=True),
    sa.Column('regime_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['rl_model_id'], ['rl_models.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knn_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_rl_model_id', sa.Integer(), nullable=False),
    sa.Column('k_neighbors', sa.Integer(), nullable=False),
    sa.Column('feature_combination', sa.String(length=200), nullable=True),
    sa.Column('seq_len', sa.Integer(), nullable=False),
    sa.Column('interval', sa.Enum('day', 'week', name='intervalenum'), nullable=False),
    sa.Column('regime_filter', sa.JSON(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('precision_buy', sa.Float(), nullable=True),
    sa.Column('precision_sell', sa.Float(), nullable=True),
    sa.Column('model_path', sa.String(length=500), nullable=True),
    sa.Column('norm_params_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('pending', 'training', 'completed', 'failed', name='modelstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_rl_model_id'], ['rl_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lstm_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source_rl_model_id', sa.Integer(), nullable=False),
    sa.Column('hidden_size', sa.Integer(), nullable=False),
    sa.Column('num_layers', sa.Integer(), nullable=False),
    sa.Column('dropout', sa.Float(), nullable=False),
    sa.Column('seq_len', sa.Integer(), nullable=False),
    sa.Column('interval', sa.Enum('day', 'week', name='intervalenum'), nullable=False),
    sa.Column('regime_filter', sa.JSON(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('precision_buy', sa.Float(), nullable=True),
    sa.Column('precision_sell', sa.Float(), nullable=True),
    sa.Column('model_path', sa.String(length=500), nullable=True),
    sa.Column('norm_params_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('pending', 'training', 'completed', 'failed', name='modelstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_rl_model_id'], ['rl_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rl_training_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rl_model_id', sa.Integer(), nullable=False),
    sa.Column('timestep', sa.Integer(), nullable=False),
    sa.Column('episode', sa.Integer(), nullable=True),
    sa.Column('reward', sa.Float(), nullable=True),
    sa.Column('loss', sa.Float(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rl_model_id'], ['rl_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_indicators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('interval', sa.Enum('day', 'week', name='intervalenum'), nullable=False),
    sa.Column('sma_5', sa.Float(), nullable=True),
    sa.Column('sma_12', sa.Float(), nullable=True),
    sa.Column('sma_24', sa.Float(), nullable=True),
    sa.Column('sma_50', sa.Float(), nullable=True),
    sa.Column('sma_100', sa.Float(), nullable=True),
    sa.Column('sma_200', sa.Float(), nullable=True),
    sa.Column('ema_20', sa.Float(), nullable=True),
    sa.Column('rsi', sa.Float(), nullable=True),
    sa.Column('srsi', sa.Float(), nullable=True),
    sa.Column('macd', sa.Float(), nullable=True),
    sa.Column('macd_signal', sa.Float(), nullable=True),
    sa.Column('macd_hist', sa.Float(), nullable=True),
    sa.Column('adx', sa.Float(), nullable=True),
    sa.Column('adx_pos', sa.Float(), nullable=True),
    sa.Column('adx_neg', sa.Float(), nullable=True),
    sa.Column('kama', sa.Float(), nullable=True),
    sa.Column('vwkama', sa.Float(), nullable=True),
    sa.Column('obv', sa.Float(), nullable=True),
    sa.Column('bb_upper', sa.Float(), nullable=True),
    sa.Column('bb_lower', sa.Float(), nullable=True),
    sa.Column('bb_mid', sa.Float(), nullable=True),
    sa.Column('tgrb_top', sa.Float(), nullable=True),
    sa.Column('tgrb_green', sa.Float(), nullable=True),
    sa.Column('tgrb_red', sa.Float(), nullable=True),
    sa.Column('tgrb_bottom', sa.Float(), nullable=True),
    sa.Column('atr', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks_list.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'date', 'interval', name='uq_indicator')
    )
    op.create_index('ix_indicator_stock_date', 'stock_indicators', ['stock_id', 'date', 'interval'], unique=False)
    op.create_table('stock_ohlcv',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('adj_close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('interval', sa.Enum('day', 'week', name='intervalenum'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks_list.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'date', 'interval', name='uq_ohlcv')
    )
    op.create_index('ix_ohlcv_stock_date', 'stock_ohlcv', ['stock_id', 'date', 'interval'], unique=False)
    op.create_table('stock_regimes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('interval', sa.Enum('day', 'week', name='intervalenum'), nullable=False),
    sa.Column('trend', sa.Enum('bullish', 'bearish', 'neutral', name='trendenum'), nullable=False),
    sa.Column('volatility', sa.Enum('high', 'low', name='volatilityenum'), nullable=False),
    sa.Column('regime_id', sa.Integer(), nullable=False),
    sa.Column('regime_confidence', sa.Float(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('is_transition', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks_list.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'date', 'interval', name='uq_regime')
    )
    op.create_index('ix_regime_id_date', 'stock_regimes', ['regime_id', 'date'], unique=False)
    op.create_index('ix_regime_stock_date', 'stock_regimes', ['stock_id', 'date', 'interval'], unique=False)
    op.create_table('ensemble_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('knn_model_id', sa.Integer(), nullable=False),
    sa.Column('lstm_model_id', sa.Integer(), nullable=False),
    sa.Column('knn_weight', sa.Float(), nullable=False),
    sa.Column('lstm_weight', sa.Float(), nullable=False),
    sa.Column('agreement_required', sa.Boolean(), nullable=False),
    sa.Column('interval', sa.Enum('day', 'week', name='intervalenum'), nullable=False),
    sa.Column('backtest_accuracy', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['knn_model_id'], ['knn_models.id'], ),
    sa.ForeignKeyConstraint(['lstm_model_id'], ['lstm_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knn_predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('knn_model_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('interval', sa.Enum('day', 'week', name='intervalenum'), nullable=False),
    sa.Column('action', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('proba_buy', sa.Float(), nullable=True),
    sa.Column('proba_sell', sa.Float(), nullable=True),
    sa.Column('proba_hold', sa.Float(), nullable=True),
    sa.Column('regime_id', sa.Integer(), nullable=True),
    sa.Column('matched_pattern_ids', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['knn_model_id'], ['knn_models.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks_list.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('knn_model_id', 'stock_id', 'date', 'interval', name='uq_knn_pred')
    )
    op.create_index('ix_knn_pred_date_action', 'knn_predictions', ['date', 'action'], unique=False)
    op.create_table('lstm_predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lstm_model_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('interval', sa.Enum('day', 'week', name='intervalenum'), nullable=False),
    sa.Column('action', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('proba_buy', sa.Float(), nullable=True),
    sa.Column('proba_sell', sa.Float(), nullable=True),
    sa.Column('proba_hold', sa.Float(), nullable=True),
    sa.Column('regime_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lstm_model_id'], ['lstm_models.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks_list.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lstm_model_id', 'stock_id', 'date', 'interval', name='uq_lstm_pred')
    )
    op.create_table('ensemble_predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ensemble_config_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('interval', sa.Enum('day', 'week', name='intervalenum'), nullable=False),
    sa.Column('action', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('knn_action', sa.Integer(), nullable=True),
    sa.Column('knn_confidence', sa.Float(), nullable=True),
    sa.Column('lstm_action', sa.Integer(), nullable=True),
    sa.Column('lstm_confidence', sa.Float(), nullable=True),
    sa.Column('agreement', sa.Boolean(), nullable=True),
    sa.Column('regime_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ensemble_config_id'], ['ensemble_configs.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks_list.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ensemble_config_id', 'stock_id', 'date', 'interval', name='uq_ensemble_pred')
    )
    op.create_table('trade_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('ensemble_prediction_id', sa.Integer(), nullable=True),
    sa.Column('variety', sa.String(length=20), nullable=False),
    sa.Column('transaction_type', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('sl_price', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'placed', 'completed', 'cancelled', 'rejected', name='orderstatus'), nullable=False),
    sa.Column('zerodha_order_id', sa.String(length=50), nullable=True),
    sa.Column('tag', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ensemble_prediction_id'], ['ensemble_predictions.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_orders')
    op.drop_table('ensemble_predictions')
    op.drop_table('lstm_predictions')
    op.drop_index('ix_knn_pred_date_action', table_name='knn_predictions')
    op.drop_table('knn_predictions')
    op.drop_table('ensemble_configs')
    op.drop_index('ix_regime_stock_date', table_name='stock_regimes')
    op.drop_index('ix_regime_id_date', table_name='stock_regimes')
    op.drop_table('stock_regimes')
    op.drop_index('ix_ohlcv_stock_date', table_name='stock_ohlcv')
    op.drop_table('stock_ohlcv')
    op.drop_index('ix_indicator_stock_date', table_name='stock_indicators')
    op.drop_table('stock_indicators')
    op.drop_table('rl_training_runs')
    op.drop_table('lstm_models')
    op.drop_table('knn_models')
    op.drop_table('golden_patterns')
    op.drop_table('backtest_results')
    op.drop_table('stocks_list')
    op.drop_table('settings')
    op.drop_table('rl_models')
    op.drop_table('nse_holidays')
    # ### end Alembic commands ###
